name: Run Python linter and formatter

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

jobs:
  checks-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: |
        ruff check .
        ruff format .
