# parodynews/management/commands/fetch_models.py
"""Refresh :class:`~parodynews.models.OpenAIModel` from the OpenAI models endpoint.

`Assistant.model` is a foreign key to `OpenAIModel`, so whatever this command
persists is exactly what the assistant form offers in its dropdown. The
`/models` endpoint returns the account's WHOLE catalogue with no capability
field on the response, so an unfiltered upsert puts image, speech,
transcription, embedding and legacy-completion ids in front of the user; picking
one fails at generation time instead of at selection time. This command filters
to the assistant-capable ids, records a description for each, and marks
delisted models unavailable rather than deleting them.
"""

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from openai import OpenAI

from parodynews.models import OpenAIModel

#: An id must start with one of these to be offered as an assistant model.
#: Deliberately an explicit allowlist rather than a heuristic: the models
#: endpoint reports no capability, so the only reviewable filter is one you can
#: read. Add a prefix here when OpenAI ships a new assistant-capable family.
ASSISTANT_MODEL_PREFIXES = ("gpt-", "o1", "o3", "o4")

#: ...and must contain none of these. Each shares a prefix above but is a
#: different endpoint: `-instruct` is legacy completions, and the audio,
#: realtime, search, transcribe, tts and image variants are modality-specific.
ASSISTANT_MODEL_EXCLUDED = (
    "-instruct",
    "-audio",
    "-realtime",
    "-search",
    "-transcribe",
    "-tts",
    "-image",
    "-moderation",
)


def is_assistant_model(model_id: str) -> bool:
    """Return True when `model_id` can back an assistant.

    Args:
        model_id: A model id as returned by `client.models.list()`.

    Returns:
        bool: True if the id matches an allowed prefix and no excluded marker.

    Examples:
        >>> is_assistant_model("gpt-4o")
        True
        >>> is_assistant_model("dall-e-3")
        False
        >>> is_assistant_model("gpt-3.5-turbo-instruct")
        False
    """
    if not model_id:
        return False
    normalized = model_id.strip().lower()
    if not normalized.startswith(ASSISTANT_MODEL_PREFIXES):
        return False
    return not any(marker in normalized for marker in ASSISTANT_MODEL_EXCLUDED)


def describe_model(model) -> str:
    """Build the stored description for one API model object.

    `OpenAIModel.description` is a non-null `TextField` that the old command
    never populated, so every row carried an empty string. The models endpoint
    has no description of its own, so compose one from what it does return.

    Args:
        model: An object from `client.models.list()` — `id`, and optionally
            `owned_by` and `created` (a Unix timestamp).

    Returns:
        str: A non-empty, human-readable description.
    """
    model_id = getattr(model, "id", "") or ""
    parts = [f"OpenAI model `{model_id}`, available to assistants."]
    owned_by = getattr(model, "owned_by", None)
    if owned_by:
        parts.append(f"Owned by {owned_by}.")
    created = getattr(model, "created", None)
    if created:
        parts.append(f"Published {created} (Unix timestamp).")
    parts.append("Description generated by `manage.py fetch_models`.")
    return " ".join(parts)


class Command(BaseCommand):
    help = (
        "Fetch assistant-capable models from the OpenAI API, record them, and "
        "mark any model OpenAI no longer lists as unavailable."
    )

    def get_client(self):
        """Build the OpenAI client.

        Isolated so tests can substitute a fake and never contact the live API.
        """
        return OpenAI()

    def handle(self, *args, **options):
        # Read the whole catalogue BEFORE touching the table. An error partway
        # through a streamed response must not leave a half-updated dropdown,
        # so the fetch fully resolves first and the writes then run in one
        # transaction.
        try:
            client = self.get_client()
            fetched = list(client.models.list())
        except Exception as exc:
            raise CommandError(
                f"Could not fetch models from the OpenAI API: {exc}. "
                "Check OPENAI_API_KEY and network access; the model table was "
                "left unchanged."
            ) from exc

        assistant_models = [
            m for m in fetched if is_assistant_model(getattr(m, "id", ""))
        ]
        seen_ids = {m.id for m in assistant_models}

        with transaction.atomic():
            for model in assistant_models:
                OpenAIModel.objects.update_or_create(
                    model_id=model.id,
                    defaults={
                        "description": describe_model(model),
                        "is_available": True,
                    },
                )
            # Delisted models keep their rows: `Assistant.model` is
            # `on_delete=SET_NULL`, so deleting one would silently unassign the
            # model from every assistant using it.
            retired = OpenAIModel.objects.filter(is_available=True).exclude(
                model_id__in=seen_ids
            )
            retired_count = retired.update(is_available=False)

        skipped = len(fetched) - len(assistant_models)
        self.stdout.write(
            self.style.SUCCESS(
                f"Recorded {len(assistant_models)} assistant-capable model(s); "
                f"skipped {skipped} non-assistant model(s); "
                f"marked {retired_count} delisted model(s) unavailable."
            )
        )
