# Generated by Django 4.2.13 on 2024-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parodynews', '0002_assistant_remove_post_title_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prompt',
            field=models.TextField(default='say this is a test'),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.TextField(default='you are a helpful assistant.'),
        ),
    ]
