# Generated by Django 5.1.4 on 2026-04-27 23:53

import django.db.models.deletion
import django.utils.timezone
import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("project_id", models.CharField(max_length=255)),
                ("org_id", models.CharField(max_length=255)),
                ("github_pages_repo", models.CharField(max_length=255)),
                (
                    "github_pages_branch",
                    models.CharField(default="main", max_length=255),
                ),
                ("github_pages_token", models.CharField(max_length=255)),
                (
                    "github_pages_post_dir",
                    models.CharField(default="posts/", max_length=255),
                ),
            ],
            options={
                "verbose_name": "App Configuration",
                "verbose_name_plural": "App Configurations",
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.CharField(
                        blank=True, max_length=225, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="system default", max_length=256, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="Describe the assistant.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        default="you are a helpful assistant.", max_length=256000
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        default="you are a helpful assistant.", max_length=256000
                    ),
                ),
                ("object", models.CharField(default="assistant", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("tools", models.JSONField(blank=True, default=list, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                (
                    "response_format",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            options={
                "verbose_name": "Assistant",
                "verbose_name_plural": "Assistants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssistantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("group_type", models.CharField(default="default", max_length=100)),
                ("sequence", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Assistant Group",
                "verbose_name_plural": "Assistant Groups",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="default_type", max_length=255)),
                (
                    "defaults",
                    models.JSONField(
                        default=list,
                        help_text="A list of model definitions with their fields and default values.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Defaults",
                "verbose_name_plural": "Field Defaults",
            },
        ),
        migrations.CreateModel(
            name="JSONSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("schema", models.JSONField()),
            ],
            options={
                "verbose_name": "JSON Schema",
                "verbose_name_plural": "JSON Schemas",
            },
        ),
        migrations.CreateModel(
            name="OpenAIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OpenAI Model",
                "verbose_name_plural": "OpenAI Models",
                "ordering": ["model_id"],
            },
        ),
        migrations.CreateModel(
            name="PostPageConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        default=None,
                        max_length=255,
                        unique=True,
                        verbose_name="instance namespace",
                    ),
                ),
                (
                    "paginated_by",
                    models.IntegerField(default=5, verbose_name="paginate size"),
                ),
            ],
            options={
                "verbose_name": "Post Page Config",
                "verbose_name_plural": "Post Page Configs",
            },
        ),
        migrations.CreateModel(
            name="PoweredBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Powered By",
                "verbose_name_plural": "Powered By",
            },
        ),
        migrations.CreateModel(
            name="AssistantGroupMembership",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "assistantgroup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parodynews.assistantgroup",
                    ),
                ),
                (
                    "assistants",
                    models.ForeignKey(
                        db_column="assistants_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parodynews.assistant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Group Membership",
                "verbose_name_plural": "Assistant Group Memberships",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="assistantgroup",
            name="assistants",
            field=models.ManyToManyField(
                related_name="assistant_group_membership",
                through="parodynews.AssistantGroupMembership",
                to="parodynews.assistant",
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="assistant_group_memberships",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistant",
                to="parodynews.assistantgroupmembership",
            ),
        ),
        migrations.CreateModel(
            name="ContentDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=100)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("slug", models.SlugField(default="slug", max_length=255)),
                ("keywords", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Detail",
                "verbose_name_plural": "Content Details",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("line_number", models.IntegerField(default=0)),
                ("content_type", models.CharField(default="text", max_length=100)),
                ("content_text", models.TextField()),
                ("prompt", models.TextField()),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contentitem",
                        to="parodynews.assistant",
                    ),
                ),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contentitem",
                        to="parodynews.contentdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Item",
                "verbose_name_plural": "Content Items",
                "ordering": ["detail", "line_number"],
            },
        ),
        migrations.AddField(
            model_name="assistant",
            name="json_schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parodynews.jsonschema",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="initial", max_length=100)),
                ("run_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="parodynews.assistant",
                    ),
                ),
                (
                    "contentitem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="parodynews.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assistant",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parodynews.openaimodel",
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_content", martor.models.MartorField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(default="draft", max_length=100)),
                (
                    "assistant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="parodynews.assistant",
                    ),
                ),
                (
                    "content_detail",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="parodynews.contentdetail",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="parodynews.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostFrontMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=100)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("slug", models.SlugField(default="slug", max_length=255)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="front_matter",
                        to="parodynews.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Front Matter",
                "verbose_name_plural": "Post Front Matters",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="postfrontmatter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="parodynews.postfrontmatter",
            ),
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("frontmatter", models.TextField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="parodynews.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Version",
                "verbose_name_plural": "Post Versions",
                "ordering": ["post", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="New Thread", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assistant_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="parodynews.assistantgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="parodynews.thread",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="parodynews.thread",
            ),
        ),
        migrations.AddIndex(
            model_name="contentdetail",
            index=models.Index(
                fields=["-published_at"], name="parodynews__publish_79983d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentdetail",
            index=models.Index(fields=["slug"], name="parodynews__slug_9209c0_idx"),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["detail", "line_number"], name="parodynews__detail__197b38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postversion",
            index=models.Index(
                fields=["post", "-version_number"],
                name="parodynews__post_id_e6602c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postversion",
            unique_together={("post", "version_number")},
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-created_at"], name="parodynews__created_7d0c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["user"], name="parodynews__user_id_cb9594_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="parodynews__created_22fd54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="parodynews__status_df0c7d_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "-created_at"], name="parodynews__user_id_51a401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="parodynews__created_57592e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "-created_at"], name="parodynews__thread__eb62f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="parodynews__status_4d1508_idx"),
        ),
    ]
