# Generated by Django 4.2.1 on 2024-10-22 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='system default', max_length=256, null=True)),
                ('description', models.CharField(blank=True, default='Describe the assistant.', max_length=512, null=True)),
                ('instructions', models.TextField(default='you are a helpful assistant.', max_length=256000)),
                ('prompt', models.TextField(default='you are a helpful assistant.', max_length=256000)),
                ('object', models.CharField(default='assistant', max_length=50)),
                ('model', models.CharField(choices=[('dall-e-3', 'dall-e-3'), ('gpt-4-1106-preview', 'gpt-4-1106-preview'), ('dall-e-2', 'dall-e-2'), ('tts-1-hd-1106', 'tts-1-hd-1106'), ('tts-1-hd', 'tts-1-hd'), ('text-embedding-3-large', 'text-embedding-3-large'), ('babbage-002', 'babbage-002'), ('gpt-4-turbo-preview', 'gpt-4-turbo-preview'), ('gpt-4o-mini', 'gpt-4o-mini'), ('gpt-4-0125-preview', 'gpt-4-0125-preview'), ('gpt-4o-mini-2024-07-18', 'gpt-4o-mini-2024-07-18'), ('text-embedding-3-small', 'text-embedding-3-small'), ('tts-1', 'tts-1'), ('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('whisper-1', 'whisper-1'), ('text-embedding-ada-002', 'text-embedding-ada-002'), ('gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k'), ('davinci-002', 'davinci-002'), ('gpt-4-turbo-2024-04-09', 'gpt-4-turbo-2024-04-09'), ('tts-1-1106', 'tts-1-1106'), ('gpt-3.5-turbo-0125', 'gpt-3.5-turbo-0125'), ('gpt-4-turbo', 'gpt-4-turbo'), ('gpt-3.5-turbo-1106', 'gpt-3.5-turbo-1106'), ('gpt-3.5-turbo-instruct-0914', 'gpt-3.5-turbo-instruct-0914'), ('gpt-3.5-turbo-instruct', 'gpt-3.5-turbo-instruct'), ('gpt-4o', 'gpt-4o'), ('gpt-4-0613', 'gpt-4-0613'), ('gpt-4o-2024-05-13', 'gpt-4o-2024-05-13'), ('gpt-4', 'gpt-4'), ('gpt-4o-2024-08-06', 'gpt-4o-2024-08-06')], default='gpt-3.5-turbo', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tools', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('response_format', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='NEED TITLE.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(default='NEED AUTHOR.', max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='slug', max_length=255)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='text', max_length=100)),
                ('prompt', models.TextField(default='say this is a test')),
                ('content', models.TextField()),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='parodynews.assistant')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='parodynews.contentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralizedCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(default='system', max_length=256)),
                ('items', models.JSONField(default=list)),
                ('model', models.CharField(default='default', max_length=256)),
                ('table', models.CharField(default='default', max_length=256)),
                ('field', models.CharField(default='default', max_length=256)),
                ('database', models.CharField(default='default', max_length=256)),
                ('category', models.CharField(default='default', max_length=256)),
                ('domain', models.CharField(default='default', max_length=256)),
                ('entity', models.CharField(default='default', max_length=256)),
                ('project', models.CharField(default='default', max_length=256)),
                ('module', models.CharField(default='default', max_length=256)),
                ('hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JSONSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='initial', max_length=100)),
                ('run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='parodynews.assistant')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='parodynews.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='MyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', martor.models.MartorField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='draft', max_length=100)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='parodynews.assistant')),
                ('content_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='parodynews.contentdetail')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='parodynews.message')),
            ],
        ),
        migrations.CreateModel(
            name='PoweredBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Thread', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostFrontMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='slug', max_length=255)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='front_matter', to='parodynews.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='parodynews.thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='parodynews.thread'),
        ),
        migrations.CreateModel(
            name='AssistantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group_type', models.CharField(default='default', max_length=100)),
                ('assistants', models.ManyToManyField(related_name='assistant_group', to='parodynews.assistant')),
            ],
        ),
        migrations.AddField(
            model_name='assistant',
            name='assistant_groups',
            field=models.ManyToManyField(blank=True, related_name='assistant', to='parodynews.assistantgroup'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='json_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parodynews.jsonschema'),
        ),
    ]
