"""
File: content.py
Description: Django models for content generation and content items
Author: Barodybroject Team <team@example.com>
Created: 2025-11-30
Last Modified: 2025-12-20
Version: 0.4.0

Dependencies:
- django: >=5.1

Usage: from parodynews.models.content import ContentDetail
"""

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class ContentDetail(models.Model):
    """Metadata for generated content pieces.

    Stores high-level information about content including title, description,
    author, and SEO-related fields. Acts as a container for ContentItems.

    Attributes:
        id (int): Auto-incrementing primary key
        title (str): Content title (max 255 chars)
        description (str): Full text description of the content
        author (str): Author name (max 100 chars)
        published_at (datetime): Publication timestamp (default: now)
        slug (str): URL-friendly identifier (max 255 chars, non-unique)
        keywords (list): JSON array of SEO keywords
        user (User): Foreign key to the content creator
        contentitem (RelatedManager): Related content items (reverse relation)
        posts (RelatedManager): Related posts (reverse relation)

    Examples:
        >>> from parodynews.models import ContentDetail
        >>> from django.contrib.auth.models import User
        >>> user = User.objects.first()
        >>> detail = ContentDetail.objects.create(
        ...     title="Breaking: Local Cat Declares Independence",
        ...     description="Satirical article about feline autonomy",
        ...     author="ParodyNews Staff",
        ...     slug="cat-independence-2024",
        ...     keywords=["cats", "parody", "independence"],
        ...     user=user
        ... )
        >>> print(detail.get_display_fields())
        ['id', 'title', 'description', 'author', 'published_at']

    Note:
        The slug field is not enforced as unique to allow reuse across
        different contexts or versions.
    """

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    author = models.CharField(max_length=100, blank=True)
    published_at = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=255, unique=False, default="slug")
    keywords = models.JSONField(default=list)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="content_details",
    )

    class Meta:
        app_label = "parodynews"
        verbose_name = "Content Detail"
        verbose_name_plural = "Content Details"
        ordering = ["-published_at"]
        indexes = [
            models.Index(fields=["-published_at"]),
            models.Index(fields=["slug"]),
        ]

    def get_display_fields(self):
        """Return list of fields to display in admin and list views.

        Returns:
            list: Field names ['id', 'title', 'description', 'author', 'published_at']
        """
        return ["id", "title", "description", "author", "published_at"]

    def __str__(self):
        """Return the content title.

        Returns:
            str: The title field value
        """
        return self.title


class ContentItem(models.Model):
    """Individual content segment generated by an assistant.

    Represents a single piece of AI-generated content within a larger
    ContentDetail. Items are automatically numbered sequentially.

    Attributes:
        id (int): Auto-incrementing primary key
        line_number (int): Sequential position within the parent ContentDetail
        content_type (str): Type of content (default: 'text', max 100 chars)
        content_text (str): The actual generated text content
        assistant (Assistant): Assistant that generated this content
        prompt (str): The prompt used to generate this content
        detail (ContentDetail): Parent content detail container
        messages (RelatedManager): Related messages (reverse relation)

    Examples:
        >>> from parodynews.models import ContentItem, ContentDetail, Assistant
        >>> detail = ContentDetail.objects.first()
        >>> assistant = Assistant.objects.get(name="News Writer")
        >>> item = ContentItem.objects.create(
        ...     content_text="In a shocking turn of events...",
        ...     content_type="paragraph",
        ...     assistant=assistant,
        ...     prompt="Write an opening paragraph about cat independence",
        ...     detail=detail
        ... )
        >>> print(item.line_number)  # Automatically set to 1 (first item)
        1
        >>> item2 = ContentItem.objects.create(
        ...     content_text="Local residents were stunned...",
        ...     assistant=assistant,
        ...     prompt="Write a follow-up paragraph",
        ...     detail=detail
        ... )
        >>> print(item2.line_number)  # Automatically set to 2
        2

    Note:
        line_number is automatically assigned on save() based on existing
        items for the same ContentDetail. Manual assignment is overridden.
    """

    id = models.AutoField(primary_key=True)
    line_number = models.IntegerField(default=0)
    content_type = models.CharField(max_length=100, default="text")
    content_text = models.TextField()

    assistant = models.ForeignKey(
        "parodynews.Assistant",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="contentitem",
    )
    prompt = models.TextField()
    detail = models.ForeignKey(
        ContentDetail, on_delete=models.CASCADE, related_name="contentitem"
    )

    class Meta:
        app_label = "parodynews"
        verbose_name = "Content Item"
        verbose_name_plural = "Content Items"
        ordering = ["detail", "line_number"]
        indexes = [
            models.Index(fields=["detail", "line_number"]),
        ]

    def get_display_fields(self):
        """Return list of fields to display in admin and list views.

        Returns:
            list: Field names ['id', 'assistant', 'prompt', 'content_text', 'detail']
        """
        return ["id", "assistant", "prompt", "content_text", "detail"]

    def save(self, *args, **kwargs):
        """Save with automatic line_number assignment.

        On creation, automatically assigns the next available line_number
        for this ContentDetail.
        """
        if not self.pk:  # Check if this is a new record
            last_item = (
                ContentItem.objects.filter(detail=self.detail)
                .order_by("-line_number")
                .first()
            )
            if last_item:
                self.line_number = last_item.line_number + 1
            else:
                self.line_number = 1
        super(ContentItem, self).save(*args, **kwargs)

    def __str__(self):
        """Return the prompt text.

        Returns:
            str: The prompt field value
        """
        return self.prompt
