version: '3'
services:
  barodydb:
    image: postgres:latest

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: barodydb
      POSTGRES_PASSWORD: postgres
      DB_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barodydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  python:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile_dev
    volumes:
      - ..:/workspace:cached

    depends_on:
      barodydb:
        condition: service_healthy

    environment:
      DB_USERNAME: postgres
      DB_NAME: barodydb
      DB_HOST: barodydb
      DB_PASSWORD: postgres
    ports:
      - "80:80"

  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --config "_config.yml,_config_dev.yml"

    volumes:
      - ./pages:/app/pages
    ports:
      - "4002:4002"
    working_dir: /app/pages
    environment:
      JEKYLL_ENV: development

volumes:
  postgres-data:
