services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: barodydb
      POSTGRES_PASSWORD: postgres

    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barodydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

    depends_on:
      db:
        condition: service_healthy

    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: barodydb   # updated from barodysql to barodydb
      POSTGRES_HOST: barodydb
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:8000"
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --config "_config.yml,_config_dev.yml"

    volumes:
      - ./pages:/app/pages
    ports:
      - "4002:4002"
    working_dir: /app/pages
    environment:
      JEKYLL_ENV: development

volumes:
  postgres-data:
