name: Build & publish dev-container

on:
  push:
    paths:
      - '.devcontainer/Dockerfile_dev'
      - 'src/requirements.txt'
      - '.github/workflows/container.yml'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Extract version information
        id: version
        run: |
          # Extract version from VERSION file if it exists, otherwise use defaults
          if [ -f "VERSION" ]; then
            VERSION=$(cat VERSION)
          else
            VERSION="0.1.0"
          fi
          
          # Calculate short git SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Calculate date tag (YYYYMMDD)
          DATE_TAG=$(date +'%Y%m%d')
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile_dev
          push: true
          tags: |
            amrabdel/barody-python:latest
            amrabdel/barody-python:${{ steps.version.outputs.version }}
            amrabdel/barody-python:${{ steps.version.outputs.version }}-${{ steps.version.outputs.date_tag }}
            amrabdel/barody-python:${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}
          cache-from: type=registry,ref=amrabdel/barody-python:buildcache
          cache-to: type=registry,ref=amrabdel/barody-python:buildcache,mode=max