name: Process Issues with OpenAI

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Run OpenAI Issue Processor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python openai/client.py \
            --issue-number "${{ github.event.issue.number }}" \
            --repo "${{ github.repository }}"
